/////////////////////////////////////////////////////////////////
//															   //
// This code is generated by a tool                            //
// https://github.com/StevenThuriot/dotnet-openapi-generator   //
//															   //
/////////////////////////////////////////////////////////////////

#nullable enable

#pragma warning disable CS8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.

using Lamashare.CLI.ApiGen.Models;

namespace Lamashare.CLI.ApiGen.Clients;

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed class AuthClient : IAuthClient
{
    private readonly System.Net.Http.HttpClient __my_http_client;
    private readonly ClientOptions __my_options;

    public AuthClient(System.Net.Http.HttpClient client, ClientOptions options)
    {
        __my_http_client = client;
        __my_options = options;
    }

    /// <summary>
    /// Generate new auth token the classic way
    /// </summary>
    public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> CreateTokenClassicWithHttpInfoAsync(ClassicLoginDto body, System.Threading.CancellationToken token = default)
    {
        var __my_request = await __my_options.CreateRequest(System.Net.Http.HttpMethod.Post, $"v1/auth/create-auth-token/classic", body, token);
        return await __my_http_client.SendAsync(__my_request, token);
    }

    /// <summary>
    /// Generate new auth token the classic way
    /// </summary>
    public async System.Threading.Tasks.Task<AuthDto?> CreateTokenClassicAsync(ClassicLoginDto body, System.Threading.CancellationToken token = default)
    {
        var __result = await CreateTokenClassicWithHttpInfoAsync(body, token);
        await __my_options.InterceptResponse(__result, token);
        return await __my_options.DeSerializeContent<AuthDto?>(__result, token);
    }

    /// <summary>
    /// Returns info about current session
    /// </summary>
    public async System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> GetSessionInfoWithHttpInfoAsync(System.Threading.CancellationToken token = default)
    {
        var __my_request = await __my_options.CreateRequest(System.Net.Http.HttpMethod.Get, $"v1/auth/current-session", token);
        return await __my_http_client.SendAsync(__my_request, token);
    }

    /// <summary>
    /// Returns info about current session
    /// </summary>
    public async System.Threading.Tasks.Task<SessionInfoDto?> GetSessionInfoAsync(System.Threading.CancellationToken token = default)
    {
        var __result = await GetSessionInfoWithHttpInfoAsync(token);
        await __my_options.InterceptResponse(__result, token);
        return await __my_options.DeSerializeContent<SessionInfoDto?>(__result, token);
    }
}

[System.CodeDom.Compiler.GeneratedCode("dotnet-openapi-generator", "8.0.0-preview.15+2dc8cfca012adb9b7e1a243f167db99da7b5cfe4")]
public interface IAuthClient
{
    /// <summary>
    /// Generate new auth token the classic way
    /// </summary>
    public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> CreateTokenClassicWithHttpInfoAsync(ClassicLoginDto body, System.Threading.CancellationToken token = default);

    /// <summary>
    /// Generate new auth token the classic way
    /// </summary>
    public System.Threading.Tasks.Task<AuthDto?> CreateTokenClassicAsync(ClassicLoginDto body, System.Threading.CancellationToken token = default);

    /// <summary>
    /// Returns info about current session
    /// </summary>
    public System.Threading.Tasks.Task<System.Net.Http.HttpResponseMessage> GetSessionInfoWithHttpInfoAsync(System.Threading.CancellationToken token = default);

    /// <summary>
    /// Returns info about current session
    /// </summary>
    public System.Threading.Tasks.Task<SessionInfoDto?> GetSessionInfoAsync(System.Threading.CancellationToken token = default);
}
